[package]
name = "meteora-activities-carbon-example"
version = "0.2.1"
edition = { workspace = true }

[dependencies]
carbon-core = { workspace = true }
carbon-log-metrics = { workspace = true }
carbon-meteora-dlmm-decoder = { workspace = true }
carbon-rpc-transaction-crawler-datasource = { workspace = true }
solana-commitment-config = { workspace = true }

async-trait = { workspace = true }
dotenv = { workspace = true }
env_logger = { workspace = true }
solana-instruction = { workspace = true }
tokio = { workspace = true, features = ["full"] }
