[package]
name = "carbon-meteora-dlmm-decoder"
version = "0.5.1"
description = "Meteora DLMM Decoder"
license = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }
serde = { workspace = true }
serde-big-array = { workspace = true }
solana-sdk = { workspace = true }
