[package]
name = "carbon-raydium-amm-v4-decoder"
version = "0.1.1"
edition = "2018"

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }
carbon-proc-macros = { workspace = true }
carbon-macros = { workspace = true }

solana-sdk = "2.0.10"
serde = "1.0.136"
serde-big-array = "0.5.1"
