[package]
name = "carbon-raydium-amm-v4-decoder"
version = "0.5.1"
description = "Raydium AMM V4 Decoder"
license = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }
serde = { workspace = true }
serde-big-array = { workspace = true }
solana-sdk = { workspace = true }
