[package]
name = "jupiter-swap-postgres"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
carbon-core = { workspace = true, features = ["postgres"] }
carbon-jupiter-swap-decoder = { workspace = true }
carbon-log-metrics = { workspace = true }
carbon-rpc-block-subscribe-datasource = { workspace = true }
solana-client = { workspace = true }

async-trait = { workspace = true }
dotenv = { workspace = true }
log = { workspace = true }
sqlx = { workspace = true }
sqlx_migrator = { workspace = true }
tokio = { workspace = true, features = ["full"] }
simplelog = "0.12"
bigdecimal = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
solana-instruction = { workspace = true }
solana-pubkey = { workspace = true }
