[package]
name = "carbon-meteora-vault-decoder"
version = "0.12.0"
description = "Meteora vault program decoder"
edition = { workspace = true }
license = { workspace = true }
readme = "README.md"
keywords = ["solana", "decoder", "meteora"]
categories = ["encoding"]

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }
serde = { workspace = true }
solana-account = { workspace = true }
solana-instruction = { workspace = true, default-features = false }
solana-pubkey = { workspace = true }
