[package]
name = "carbon-bonkswap-decoder"
version = "0.12.0"
description = "Carbon BonkSwap Decoder"
edition = { workspace = true }
license = { workspace = true }
readme = "README.md"
keywords = ["solana", "decoder", "bonkswap"]
categories = ["encoding"]

[lib]
crate-type = ["rlib"]

[features]
default = []
serde = ["dep:serde"]
postgres = ["carbon-core/postgres", "dep:sqlx", "dep:async-trait", "dep:sqlx_migrator", "serde"]
graphql = ["carbon-core/graphql", "dep:juniper", "serde"]

[dependencies]
# Core dependencies
carbon-core = { workspace = true }
solana-account = { workspace = true }
solana-instruction = { workspace = true, default-features = false }
solana-pubkey = { workspace = true }
borsh = { workspace = true }

# Serialization (optional)
serde = { workspace = true, features = ["derive"], optional = true }

# Postgres dependencies (optional)
async-trait = { workspace = true, optional = true }
sqlx = { workspace = true, features = ["postgres", "rust_decimal"], optional = true }
sqlx_migrator = { workspace = true, optional = true }

# GraphQL dependencies (optional)
juniper = { workspace = true, optional = true }

[dev-dependencies]
carbon-test-utils = { workspace = true }
