[package]
name = "log-events-example"
version = "0.12.0"
edition = { workspace = true }

[dependencies]

async-trait = { workspace = true }
carbon-core = { workspace = true }
carbon-log-metrics = { workspace = true }
carbon-raydium-cpmm-decoder = { workspace = true }
carbon-yellowstone-grpc-datasource = { workspace = true }
dotenv = { workspace = true }
env_logger = { workspace = true }
solana-instruction = { workspace = true }
tokio = { workspace = true, features = ["full"] }
yellowstone-grpc-proto = { workspace = true }

[dependencies.rustls]
default-features = false
features = ["std", "aws_lc_rs"]
version = "0.23.35"
