[package]
name = "kamino-limit-order-decoder"
version = "0.7.0"
description = "Kamino Limit Order Decoder"
edition = { workspace = true }
license = { workspace = true }
readme = "README.md"
repository = { workspace = true }
keywords = ["solana", "decoder", "kamino", "limit-order"]
categories = ["encoding"]

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }
carbon-macros = { workspace = true }
carbon-proc-macros = { workspace = true }
serde = { workspace = true }
serde-big-array = { workspace = true }
solana-pubkey = { workspace = true }
solana-sdk = { workspace = true }
