[package]
name = "carbon-pancake-swap-decoder"
version = "0.11.0"
edition = { workspace = true }

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }
solana-account = { workspace = true }
solana-instruction = { workspace = true }
solana-pubkey = { workspace = true }
serde = { workspace = true }
serde-big-array = { workspace = true }
