[package]
name = "carbon-yellowstone-grpc-datasource"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
yellowstone-grpc-proto = { version = "=1.15.0+solana.2.0.10", git = "https://github.com/rpcpool/yellowstone-grpc.git" }
yellowstone-grpc-client = { version = "=1.16.2+solana.2.0.10", git = "https://github.com/rpcpool/yellowstone-grpc.git" }
futures = "0.3.30"
futures-util = "0.3.30"
carbon-core = { workspace = true }
solana-sdk = { workspace = true }
solana-transaction-status = { workspace = true }
solana-client = { workspace = true }
tokio = { version = "1.40.0", features = ["full"] }
async-trait = "0.1.83"
log = "0.4.22"
env_logger = "0.11.5"
tokio-util = "0.7.12"
