[package]
name = "dynamic-bonding-curve-decoder"
version = "0.9.1"
edition = { workspace = true }

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }
solana-account = { workspace = true }
solana-instruction = { workspace = true }
solana-pubkey = { workspace = true }
serde = { workspace = true }
serde-big-array = { workspace = true }
