[package]
name = "testing-crate"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
carbon-core = { path = "../../crates/core" }
carbon-macros = { path = "../../crates/macros" }
carbon-proc-macros = { path = "../../crates/proc-macros" }
futures = "0.3.30"
async-trait = "0.1.82"
solana-sdk = "2.0.9"
solana-transaction-status = "2.0.9"
env_logger = "0.11.5"
paste = "1.0.15"
spl-token = "6.0.0"
mpl-token-metadata = "4.1.2"
log = "0.4.22"
serde = "1.0.136"
solana-client = "2.0.9"
bs58 = "0.5.1"
once_cell = "1.17.1"
