[package]
name = "marginfi-v2-decoder"
version = "0.1.4"
description = "MarginfiV2 Decoder"
edition = { workspace = true }
license = { workspace = true }
readme = "README.md"
repository = { workspace = true }
keywords = ["solana", "decoder", "marginfi", "marginfiV2"]
categories = ["encoding"]

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }
carbon-proc-macros = { workspace = true }
carbon-macros = { workspace = true }
solana-sdk = { workspace = true }
serde = { workspace = true }

