[package]
name = "carbon-memo-program-decoder"
version = "0.12.0"
description = "Memo Program Decoder"
license = { workspace = true }
edition = { workspace = true }
readme = "README.md"
repository = { workspace = true }
keywords = ["solana", "decoder", "memo"]
categories = ["encoding"]

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }
serde = { workspace = true }
solana-instruction = { workspace = true, default-features = false }
spl-memo-interface = { workspace = true }
