[package]
name = "carbon-circle-token-messenger-v2-decoder"
version = "0.12.0"
description = "Circle CCTP Token Messenger V2 Decoder"
homepage = "https://github.com/circlefin/solana-cctp-contracts"
edition = { workspace = true }
license = { workspace = true }
readme = "README.md"
repository = { workspace = true }
keywords = ["solana", "decoder", "circle", "cctp"]
categories = ["encoding"]

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }
solana-account = { workspace = true }
solana-instruction = { workspace = true, default-features = false }
solana-pubkey = { workspace = true }
serde = { workspace = true }
