[package]
name = "carbon-okx-dex-decoder"
version = "0.7.0"
description = "OKX DEX Decoder"
license = { workspace = true }
edition = { workspace = true }
readme = "README.md"
keywords = ["solana", "decoder", "okx"]
categories = ["encoding"]

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }
serde = { workspace = true }
solana-pubkey = { workspace = true }
solana-sdk = { workspace = true }
