[package]
name = "carbon-token-2022-decoder"
version = "0.5.1"
description = "Carbon Token 2022 Decoder"
edition = { workspace = true }
license = { workspace = true }

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }
carbon-macros = { workspace = true }
carbon-proc-macros = { workspace = true }
serde = { workspace = true }
serde-big-array = { workspace = true }
solana-sdk = { workspace = true }
