[package]
name = "carbon-raydium-cpmm-decoder"
version = "0.5.1"
description = "Raydium CPMM Decoder"
edition = { workspace = true }
license = { workspace = true }

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }
carbon-macros = { workspace = true }
carbon-proc-macros = { workspace = true }

solana-sdk = { workspace = true }

serde = { workspace = true }
