[package]
name = "carbon-fluxbeam-decoder"
version = "0.7.0"
description = "Fluxbeam Decoder"
edition = { workspace = true }
license = { workspace = true }
readme = "README.md"
repository = { workspace = true }
keywords = ["solana", "decoder", "fluxbeam"]
categories = ["encoding"]

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }
carbon-macros = { workspace = true }
carbon-proc-macros = { workspace = true }
serde = { workspace = true }
solana-pubkey = { workspace = true }
solana-sdk = { workspace = true }

[dev-dependencies]
carbon-test-utils = { workspace = true }
