[package]
name = "carbon-swig-decoder"
version = "0.12.0"
description = "Swig Decoder"
license = { workspace = true }
edition = { workspace = true }
readme = "README.md"
repository = { workspace = true }
keywords = ["solana", "decoder", "swig"]
categories = ["encoding"]

[lib]
crate-type = ["rlib"]

[features]
default = []

serde = ["dep:serde-big-array"]

postgres = [
    "carbon-core/postgres",
    "dep:sqlx",
    "dep:async-trait",
    "dep:sqlx_migrator",
    "serde",
]

graphql = [
    "carbon-core/graphql",
    "dep:juniper",
    "dep:base64",
    "postgres",
    "serde",
]

[dependencies]
carbon-core = { workspace = true, features = ["macros"], default-features = false }
borsh = { workspace = true, features = ["derive"] }
solana-pubkey = { workspace = true }
solana-account = { workspace = true }
solana-instruction = { workspace = true, default-features = false, features = ["std"] }
serde_json = { workspace = true }

serde = { workspace = true }
serde-big-array = { workspace = true, optional = true }

sqlx = { workspace = true, optional = true }
async-trait = { workspace = true, optional = true }
sqlx_migrator = { workspace = true, optional = true }

juniper = { workspace = true, optional = true }
base64 = { workspace = true, optional = true }

[dev-dependencies]
carbon-test-utils = { workspace = true }
