[package]
name = "kamino-farms-decoder"
version = "0.6.1"
edition = { workspace = true }
description = "Kamino Farms Decoder"
license = { workspace = true }
readme = "README.md"
repository = { workspace = true }
keywords = ["solana", "decoder", "kamino", "farms", "kamino-farms"]
categories = ["encoding"]
[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }
carbon-macros = { workspace = true }
carbon-proc-macros = { workspace = true }
serde = { workspace = true }
solana-sdk = { workspace = true }
