[package]
name = "carbon-lifinity-amm-v2-decoder"
version = "0.9.1"
description = "Lifinity AMM V2 Decoder"
edition = { workspace = true }
license = { workspace = true }
readme = "README.md"
repository = { workspace = true }
keywords = ["solana", "decoder", "lifinity"]
categories = ["encoding"]

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }
serde = { workspace = true }
solana-account = { workspace = true }
solana-instruction = { workspace = true, default-features = false }
solana-pubkey = { workspace = true }

[dev-dependencies]
carbon-test-utils = { workspace = true }
