[package]
name = "kamino-alerts-carbon-example"
version = "0.2.1"
edition = { workspace = true }
license = { workspace = true }

[dependencies]
carbon-core = { workspace = true }
carbon-kamino-lending-decoder = { workspace = true }
carbon-yellowstone-grpc-datasource = { workspace = true }

async-trait = { workspace = true }
dotenv = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
solana-account = { workspace = true }
solana-instruction = { workspace = true }
tokio = { workspace = true, features = ["full"] }
yellowstone-grpc-proto = { workspace = true }
