[package]
name = "pumpswap-alerts-carbon-example"
version = "0.2.1"
edition = { workspace = true }

[dependencies]
carbon-core = { workspace = true }
carbon-helius-laserstream-datasource = { workspace = true }
carbon-log-metrics = { workspace = true }
carbon-pump-swap-decoder = { workspace = true }

async-trait = { workspace = true }
dotenv = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
solana-instruction = { workspace = true }
solana-native-token = { workspace = true }
tokio = { workspace = true, features = ["full"] }
yellowstone-grpc-proto = { workspace = true }

[dependencies.rustls]
default-features = false
features = ["std", "aws_lc_rs"]
version = "0.23.35"
