[package]
name = "sharky-offers-carbon-example"
version = "0.2.1"
edition = { workspace = true }
[package.metadata.cargo-machete]
ignored = ["serde", "solana-instruction"]

[dependencies]
carbon-core = { workspace = true }
carbon-log-metrics = { workspace = true }
carbon-rpc-program-subscribe-datasource = { workspace = true }
carbon-sharky-decoder = { workspace = true }
solana-account-decoder = { workspace = true }
solana-client = { workspace = true }
solana-instruction = { workspace = true, default-features = false }
solana-pubkey = { workspace = true }
solana-account = { workspace = true }

anyhow = { workspace = true }
async-trait = { workspace = true }
dotenv = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true }
