[package]
name = "carbon-prometheus-metrics"
version = "0.11.0"
description = "Prometheus Metrics"
license = { workspace = true }
edition = { workspace = true }
readme = "README.md"
repository = { workspace = true }
keywords = ["solana", "prometheus", "metrics"]
categories = ["encoding"]

[dependencies]
carbon-core = { workspace = true }

log = { workspace = true }

[lib]
crate-type = ["rlib"]
