[package]
name = "carbon-log-metrics"
version = "0.4.1"
description = "Log Metrics"
license = { workspace = true }
edition = { workspace = true }

[dependencies]
carbon-core = { workspace = true }

async-trait = { workspace = true }
log = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[lib]
crate-type = ["rlib"]
