[package]
name = "carbon-log-metrics"
version = "0.11.0"
description = "Log Metrics"
license = { workspace = true }
edition = { workspace = true }
readme = "README.md"
repository = { workspace = true }
keywords = ["solana", "log", "metrics"]
categories = ["encoding"]

[dependencies]
carbon-core = { workspace = true }

log = { workspace = true }


[lib]
crate-type = ["rlib"]
