[package]
name = "pumpfun-alerts-carbon-example"
version = "0.2.1"
edition = { workspace = true }

[dependencies]
carbon-core = { workspace = true }
carbon-helius-atlas-ws-datasource = { workspace = true }
carbon-pumpfun-decoder = { workspace = true }
solana-client = { workspace = true }
solana-pubkey = { workspace = true }
solana-native-token = { workspace = true }
solana-transaction-status = { workspace = true }

async-trait = { workspace = true }
dotenv = { workspace = true }
env_logger = { workspace = true }
helius = { workspace = true }
log = { workspace = true }
tokio = { workspace = true, features = ["full"] }
