[package]
name = "carbon-system-program-decoder"
version = "0.12.0"
description = "System Program Decoder"
license = { workspace = true }
edition = { workspace = true }
readme = "README.md"
repository = { workspace = true }
keywords = ["solana", "decoder", "system"]
categories = ["encoding"]

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }
serde = { workspace = true }
solana-account = { workspace = true }
solana-instruction = { workspace = true, default-features = false }
solana-pubkey = { workspace = true }
solana-system-interface = { workspace = true }

[dev-dependencies]
carbon-test-utils = { workspace = true }
