[package]
name = "carbon-raydium-clmm-decoder"
version = "0.4.1"
description = "Raydium CLMM Decoder"
edition = { workspace = true }
license = { workspace = true }

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }
carbon-macros = { workspace = true }
carbon-proc-macros = { workspace = true }
serde = { workspace = true }
solana-sdk = { workspace = true }
